language: node_js
node_js:
- '0.12'
sudo: false
before_script:
- gem install sass
- npm install -g bower grunt grunt-cli grunt-karma karma --save-dev
- bower install --save
- npm install grunt-contrib-sass --save
script: grunt test
after_success:
- rvm 1.9.3 do gem install net-ssh -v 2.9.2
- bash ./travis/deploy.sh
